<?xml version="1.0"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://localhost:8091" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Bookcatalog.BookService" targetNamespace="http://localhost:8091">
  <types>
    <xsd:schema targetNamespace="http://localhost:8091">
      <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
    </xsd:schema>
  </types>
  <portType name="Bookcatalog.BookServicePort"/>
  <binding name="Bookcatalog.BookServiceBinding" type="tns:Bookcatalog.BookServicePort">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  </binding>
  <service name="Bookcatalog.BookServiceService">
    <port name="Bookcatalog.BookServicePort" binding="tns:Bookcatalog.BookServiceBinding">
      <soap:address location="http://localhost:8091"/>
    </port>
  </service>
</definitions>
